# Generated by Django 5.2.8 on 2025-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("total_count", models.IntegerField()),
                ("avg_flowrate", models.FloatField()),
                ("avg_pressure", models.FloatField()),
                ("avg_temperature", models.FloatField()),
                ("type_distribution", models.JSONField()),
            ],
            options={
                "ordering": ["-upload_time"],
            },
        ),
    ]
