# Generated by Django 5.2.8 on 2025-11-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhistory",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
